### ISSUE TITLE
Node.jsの対象Versionを6にする

### ISSUE THREAD

**Issue by FaviusTy** [NKMR6194/saider#11]
2016年11月の時点でNode.jsのLTSが4から6に変更されています。  
https://nodejs.org/ja/

これに合わせて推奨Versionを常に最新のLTSに合わせるように追従するのが良いと思います。

同時に現行のbabel-presets-es2015 も babel-preset-es2015-node6 に切り替えることにより、V8に実装されている機能のトランスパイルが発生せず、ビルド・依存モジュールともにコンパクトになるのでお勧めしたいです。

**Comment by ysakasin** [comment]
早速移行しました。
issueありがとうございます。
