### ISSUE TITLE
config.jsonの指定に関係なく待ち受けportが31102

### ISSUE THREAD

**Issue by daicyan** [NKMR6194/saider#14]
src/server.jsにて、config.jsonの指定に関係なく3行目のport=31102しか設定さらず、console.log出力も31102固定になっています。

**Comment by ysakasin** [comment]
報告ありがとうございます。

把握しているので、次回リリースまでには修正します。

**Comment by FaviusTy** [comment]
#19

**Comment by ysakasin** [comment]
@daicyan 

@FaviusTy さんの協力により修正されました。masterには取り込み済みです。
また、次回リリースで反映予定です。
