### ISSUE TITLE
インデント幅を `2` にすべきでは？

### ISSUE THREAD

**Issue by FaviusTy** [NKMR6194/saider#18]
前から気になっていたのですが、インデント幅は `4` について強いポリシーをお持ちでしょうか？  
昨今の javascript ではインデント幅を `2` にする慣習が支配的であるので、ここに強いポリシーがないのであれば `2` に合わせてもらえると個人的には嬉しいのですが…。  
(私自身が公私あわせて js 系のコードベースに触れる機会がかなり多いのもありますが、エディタの設定周りで特別に微調整が必要だったりとちょっと敷居を感じています)

**Comment by ysakasin** [comment]
ご存知かわかりませんが、Saiderも最初は2 spaceインデントでした。
プロジェクトとしてそれなりに整備するに当たって、 [Nekochat](https://github.com/ukatama/nekochat)というプロジェクトを参考にしたのですが、そちらで4 spaceを採用していました。結果、該当コミット bc862d9d08cfec1dd1e71dc3846892341ef20fc3 で一気に4 spaceに意向したという経緯があります。

個人的にも2 spaceは好きですし、さらに移行する理由が増強されれば、再度2 spaceに戻ってもいいのかなとは思います。

**Comment by ysakasin** [comment]
nodejs/node を見た所、2 spaceっぽいので、処理系のデファクトスタンダードに合わせて2 spaceに再度移行しようと思います。

**Comment by FaviusTy** [comment]
対応いただけるようで、ありがとうございます。
助かります 😃

**Comment by ysakasin** [comment]
変更しました
