### ISSUE TITLE
cleanroomがエラーになる

### ISSUE THREAD

**Issue by daicyan** [NKMR6194/saider#5]
npm run cleanroomを実行したところ、以下のようなエラーが出ます。

> Saider@0.5.0 cleanroom /home/saider/saider
> node scripts/clean.js

/home/saider/saider/scripts/clean.js:6
const datastore = new DataStore(config);
                  ^

TypeError: DataStore is not a constructor
    at Object.<anonymous> (/home/saider/saider/scripts/clean.js:6:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

npm ERR! Linux 4.8.4-1-ARCH
npm ERR! argv "/home/saider/.nvm/versions/node/v7.0.0/bin/node" "/home/saider/.nvm/versions/node/v7.0.0/bin/npm" "run" "cleanroom"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! Saider@0.5.0 cleanroom: `node scripts/clean.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Saider@0.5.0 cleanroom script 'node scripts/clean.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Saider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/clean.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Saider
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Saider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saider/saider/npm-debug.log

**Comment by ysakasin** [comment]
たしかにバグですね。報告ありがとうございます。

原因は判明したのですが、どう解決するか検討中です。

**Comment by FaviusTy** [comment]
この件ですが、 `Datastore` class を直接 default として export するのが想定している使い方ではないかと思いました。  

``` js
export default class DataStore {
```

``` js
const Datastore = require('../lib/datastore');
const ds = new Datastore();
```

**Comment by ysakasin** [comment]
対応が完了しました。
