### ISSUE TITLE
datastoreでRedisAPIの非同期制御の待ち合わせができていない

### ISSUE THREAD

**Issue by FaviusTy** [NKMR6194/saider#8]
`node-redis` のRedisコマンドラッパーAPIはすべて非同期処理なので、以下の `deleteRoom` は各コマンドのRedis側の完了を待たずにプログラムの処理が進んでしまいます。  

```js
    deleteRoom(id) {
        client.hdel('map', id);
        client.del(key('memo', id));
        client.hdel('memo_id', id);
        client.del(key('result', id));
        client.hdel('room', id);
        client.hdel('password', id);
        client.hdel('dicebot', id);
        client.hdel('time', id);
        client.hdel('piece_id', id);
        client.del(key('piece', id));
    }
```

Redis自体が高速に動作するため、ほとんどの場合は問題なく動作しますが、例えば以下のコードは `quit` 実行時点で `deleteRoom` の操作が全て完了されている事を保証できません。  
```js
const ds = new Datasource();
ds.deleteRoom(1);
ds.quit();
```

node-redis のAPIは全て callback を引数に受け取れるようになっていますが、callbackだけでは `deleteRoom` のような多数の処理の待ち合わせを書くのは大変なので何かしら制御用のライブラリなどを用いた方が良いと思います。  

蛇足ですが、 `deleteRoom` のような処理は `client.batch()` を使った方が良いかもしれません(redisをそこまで詳細に把握していないので断言できかねるのですが…)

**Comment by ysakasin** [comment]
今後の方針として、データ格納をRedisではなくsqlite等のSQL系のデータベースに変更する予定なので、あまり厳密に考えないつもりです。

あと、このアプリケーション内では、現在Redisとの接続は明示的にquitしていません。
Redisとの接続が遮断されるような状況は、プロセスがkillされたり、障害で落ちたりする場合です。ご指摘のように整合性が崩れるような状況は考えられますが、このようなデータ保存形式でRedisを使っている時点で整合性を保証するのは困難ですし、致し方ないポイントだと思われます。

**Comment by FaviusTy** [comment]
理解しました。  
このIssueは `clean.js` が以下のような実装になっていたのでそこが引っかかったのがきっかけです。  

``` js

datastore.getTimes((times) => {
  datastore.quit();
  for (let room in times) {
    if (time - times[room] >= limit) {
      datastore.deleteRoom(room);
      console.log("Delete:" + room);
    }
  }
  console.log("Compleated clean rooms.");
});
```

この場合、なぜか `datastore.quit` がそもそも `datastore.deleteRoom` より前に実施されてしまうのでそもそも `deleteRoom` 実行時には close されてしまって私の環境では失敗してしまったのですが。  

末尾で `datastore.quit` を実行するとしても全てのループ処理中の `deleteRoom` の処理完了前に quit が走って不特定に失敗する可能性が残ってしまいます。 

とはいえ、今後SQLiteに切り替えるのであれば無用な話ではあると思います。
(個人的にはRDBSは永続化層としてはともかく、ws通信で発生する高頻度なr/w先の対象としてはかえって難しいのではないかとも感じていますが…)

**Comment by ysakasin** [comment]
`clean.js` の `quit()` は……　完全にバグですね。ありがとうございます。

RDBSにしても、Writeは書き込みのたびに発生しますが、Readは入室時1回のみすればいいので、あまり問題にならないのではないかと思っています。加えて、各種IDやTimestampの発行・よみ出しがRedisだとやはり面倒になっているので、RDBSにすることでそこら辺をシステムにお任せできればなと思っています。 RDBS移行に関してもissue立てますので、ご意見あればお願いします。
